apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-scrollfeed-ui
  namespace: scrollfeed-dev
  labels:
    app: dev-scrollfeed-ui
    environment: dev
    team: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-scrollfeed-ui
  template:
    metadata:
      labels:
        app: dev-scrollfeed-ui
        environment: dev
        team: platform
    spec:
      containers:
        - name: dev-scrollfeed-ui
          image: justscroll/scrollfeed-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: dev-scrollfeed-ui
  namespace: scrollfeed-dev
  labels:
    app: dev-scrollfeed-ui
    environment: dev
    team: platform
spec:
  selector:
    app: dev-scrollfeed-ui
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
