apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

# Removed commonLabels to prevent service selector mismatch
# The deployment and service already have consistent app=scrollfeed-ui labels
