apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

commonLabels:
  app.kubernetes.io/name: scrollfeed-ui
  app.kubernetes.io/component: frontend
  environment: prod
